.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "README" "" "September 2015" "" ""
Script to learn bash scripting\.
.
.P
 \fIhttps://travis\-ci\.org/danog/learn\-bash\fR
.
.P
This project is licensed under the GPLv3 license\.
.
.P
To install this script run the following command on any Linux/Unix system, including Mac OS X and iOS\.
.
.IP "" 4
.
.nf

wget http://daniilgentili\.magix\.net/learn\.sh && chmod +x learn\.sh
.
.fi
.
.IP "" 0
.
.P
And execute the script with this command: \fB\./learn\.sh\fR
.
.P
Happy learning! Daniil Gentili
